ALTER TABLE Cars
ADD FOREIGN KEY (CLIENT_ID) REFERENCES Clients(ID);

ALTER TABLE Certificates
ADD FOREIGN KEY (CAR_SERIAL_NUMBER) REFERENCES Cars(SERIAL_NUMBER);
ALTER TABLE Certificates
ADD FOREIGN KEY (WORKER_ID) REFERENCES Workers(ID);


ALTER TABLE Comments
ADD FOREIGN KEY (WORKER_ID) REFERENCES Workers(ID);
ALTER TABLE Comments
ADD FOREIGN KEY (CERTIFICATE_NUMBER) REFERENCES Certificates(NUMBER);